name: Fast update CSV

on:
  schedule:
    - cron: "0 12 * * *"   # daily 7 AM CT
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Python script
        run: |
          pip install pandas openpyxl
          python update_liens.py

          - name: Commit and push safely
          run: |
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add liens.csv || true
            git commit -m "auto-update liens CSV" || echo "No changes"
  
            # Always update the local main with the remote before pushing
            git fetch origin main
            git rebase origin/main || git rebase --skip
  
            # Push final version
            git push origin HEAD:main

